sonar.projectKey=YazilimKaliteGuvencesiTaskboard
sonar.projectName=YazilimKaliteGuvencesiTaskboard
sonar.projectVersion=1.0
sonar.sources=src,client/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.spec.ts
sonar.tests=src/tests,client/src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://host.docker.internal:9000
sonar.login=squ_8cc1a59c4411405c546ff55281661593e377198b
